Dependencias

diff --git a/bin/generate-hmac-secret b/bin/generate-hmac-secret
--- a/bin/generate-hmac-secret
+++ b/bin/generate-hmac-secret
@@ -1,9 +1,16 @@
 #!/usr/bin/env bash
 
+for i in openssl base64 gettext; do
+  if which $i &>/dev/null; then
+    printf "$(gettext "%s is missing on PATH")" $i
+    exit 1
+  fi
+done
+
 if test -z "$1" ; then
   printf "$(gettext "Generates an hmac secret\n\nUsage:\t%s \"shared_secret\" \"your_secret\"\n")" \
          ${0##*/}
   exit 0
 fi
 
-echo -n "$2" | openssl sha1 -hmac "$1" -binary | base64
+printf "$2" | openssl sha1 -hmac "$1" -binary | base64
